#!/usr/bin/env bash
# script displays Best School 10 times
# at 9th iteration display Best School then Hi
# Uses if statement

i=1
while [[ $i -le 10 ]]; do
    echo "Holberton School"

    if [[ $i -eq 9 ]];
    then
	echo Hi
    fi
    let i+=1
done
